name: Scala CI and commitlint
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
  steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - uses: actions/checkout@v2
    - name: Formatting
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
    - uses: TriPSs/conventional-changelog-action@v3
    - name: Conventional Changelog Action
    - uses: wagoid/commitlint-github-action@v1
      with:
        configFile: ./.commitlintrc.js
    - name: commitlint
      # with:
        # github-token: ${{ secrets.github_token }}
